apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversaoweb
  template:
    metadata:
      labels:
        app: conversaoweb
    spec:
      containers:
        - name: conversaoweb
          image: damatomos/conversao-temperatura:latest
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversaoweb
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort